name: trigger
on: 
  push:
    branches: [main]

env:
  UPSTREAM_GIT: https://gitlab.manjaro.org/manjaro-arm/applications/arm-profiles.git
  BASE_BRANCH: main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v4
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fetch-depth: 0
    - 
      name: fetch upstream
      run: |
        git remote add upstream ${UPSTREAM_GIT}
        git fetch upstream
    - 
      name: rebase
      run: |
        git config --global user.name "Repo Update Bot"
        git config --global user.email "info@manjaro-sway.download"
        git pull --rebase upstream ${BASE_BRANCH}
        git push --force-with-lease
    - 
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        repository: manjaro-sway/manjaro-sway
        event-type: image_profile_update